build:
  image: node:lts
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

test:
  image: node:lts
  stage: test
  script:
    - npm ci
    - npm run test:unit

lint:
  image: node:lts
  stage: test
  script:
    - npm ci
    - npm run lint
